### ISSUE TITLE
Camille Python 3.9 support

### ISSUE THREAD

**Issue by IvanKolesarEquinor** [equinor/camille#206]
Currently we are having support up to python 3.8, but Python 3.9 is already available since Sept. 2020 (or so). We should put a support for it as well.

For Python 3.9 several small thinks would have to be thought to get a painless:
-  remove Pandas version limit of 1.0.3. That will have an implication on our tests as pandas.testing.assert_series_equal now checks for series frequency as well
- need to figure out various other changes (or deprecations) from version 1.1.0 [https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.1.0.html](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.1.0.html)

**Comment by LauraSManns** [comment]
Merge together with #197
